"""initial migration

Revision ID: 273c7d2bbe63
Revises: 
Create Date: 2020-09-25 00:40:29.352663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273c7d2bbe63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('roles',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
                    sa.Column('permission', sa.INTEGER(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('users',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
                    sa.Column('role_id', sa.INTEGER(), nullable=True),
                    sa.Column('password_hash', sa.VARCHAR(length=2048), nullable=True),
                    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('projects',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('title', sa.VARCHAR(length=512), nullable=True),
                    sa.Column('image_link', sa.VARCHAR(length=2048), nullable=True),
                    sa.Column('short_description', sa.TEXT(), nullable=True),
                    sa.Column('content', sa.TEXT(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )

    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    op.drop_table('projects')
    op.drop_table('users')
    # ### end Alembic commands ###
